<main data-bs-spy="scroll" data-bs-target="#navbarNav">

<div id="admin_login" class="space d-flex justify-content-center mt-5">
    <form method="post" action="">
        <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 row-gap-3 mb-4">
            <div class="col d-grid">
                <label for="admin-login">E-Mail</label>
                <input type="admin_mail" class="form-control" id="admin_mail">
                <label for="admin-pwd">Passwort</label>
                <input type="password" class="form-control" id="admin_pwd">
                <button type="submit" class="btn btn-primary" id="adminLoginBtn" href="">Login</button>
            </div>
        </div>
    </form>
</div>
    

</main>