<main data-bs-spy="scroll" data-bs-target="#navbarNav">

    <section id="impressum" class="space">

        <div class="container">
            <div class="row">
                <div class="col-12 text-center">
                <h1>Impressum</h1>
                </div>
                <div class="col-12">
                    
                    <h2>Angaben gemäß § 5 TMG</h2>
                    <p><strong>Max Mustermann</strong><br>
                        Musterstraße 1<br>
                        12345 Musterstadt<br>
                        Deutschland</p>
                    <h2>Kontakt</h2>
                    <p>Telefon: +49 (0) 123 4567890<br>
                        E-Mail: <a href="mailto:max@example.com">max@example.com</a></p>
                    <h2>Umsatzsteuer-ID</h2>
                    <p>Umsatzsteuer-Identifikationsnummer gemäß §27 a Umsatzsteuergesetz: DE123456789</p>
                    <h2>Haftungsausschluss</h2>
                    <p>Die Inhalte dieser Webseite wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte übernehmen wir jedoch keine Gewähr.</p>
                    <h2>Verbraucherstreitbeilegung</h2>
                    <p>Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p>

                </div>
            </div>
        </div>

    </section>

</main>