<main data-bs-spy="scroll" data-bs-target="#navbarNav">

    <section id="hero" class="space d-flex flex-column justify-content-center">
        <?php require('templates/content/hero.phtml'); ?>
    </section>

    <section id="foodcarousel" class="space">
        <?php require('templates/content/foodcarousel.phtml'); ?>
    </section>

    <section id="restaurant" class="space">
        <?php require('templates/content/restaurant.phtml'); ?>
    </section>

    <section id="foodmenu" class="space">
        <?php require('templates/content/foodmenu.phtml'); ?>
    </section>

    <section id="team" class="space">
        <?php require('templates/content/team.phtml'); ?>
    </section>

    <section id="contest" class="space">
        <?php require('templates/content/contest.phtml'); ?>
    </section>

    <?php if (!isset($_SESSION['user'])): ?>
        <?php if (isset($data['registration_success'])): ?>
            <div class="alert alert-success alert-dismissible fade show fixed-top col-lg-6 mt-5 mx-auto" role="alert">
                <?= $data['registration_success'] ?>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        <?php else: ?>
            <section id="login" class="space">
                <?php require('templates/content/user_registration.phtml'); ?>
            </section>
        <?php endif; ?>
    <?php endif; ?>


    <section id="contact" class="space-top">
        <?php require('templates/content/contact.phtml'); ?>
    </section>

</main>