<main data-bs-spy="scroll" data-bs-target="#navbarNav">

    <section id="hero" class="space d-flex flex-column justify-content-center">
        <?php require('templates/content/hero.phtml'); ?>
    </section>

    <section id="foodcarousel" class="space">
        <?php require('templates/content/foodcarousel.phtml'); ?>
    </section>

    <section id="restaurant" class="space">
        <?php require('templates/content/restaurant.phtml'); ?>
    </section>

    <section id="foodmenu" class="space">
        <?php require('templates/content/foodmenu.phtml'); ?>
    </section>

    <section id="team" class="space">
        <?php require('templates/content/team.phtml'); ?>
    </section>

    <section id="contest" class="space">
        <?php require('templates/content/contest.phtml'); ?>
    </section>

    <section id="login" class="space">
        <?php require('templates/content/user_registration.phtml'); ?>
    </section>

    <section id="contact" class="space-top">
        <?php require('templates/content/contact.phtml'); ?>
    </section>

</main>