<div class="container">
    <div class="row py-3">
        <div class="col">
            <ul class="nav justify-content-center">
                <li class="nav-item">
                    <span class="nav-link disabled text-white"><small>Copyright © All rights reserved.</small></span>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="templates/views/impressum.phtml"><small>Impressum</small></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="templates/views/datenschutz.phtml"><small>Datenschutz</small></a>
                </li>
            </ul>
        </div>
    </div>
</div>