<nav class="navbar navbar-expand-lg">
    <div class="container">

        <a href="/">
            <img src="/src/img/logo.png" alt="logo" width="200">
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-lg-end" id="navbarNav">
            <ul class="navbar-nav align-items-center">

                <li class="nav-item">
                    <a class="nav-link" href="#foodmenu">
                        <span>Speisekarte</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#team">
                        <span>Team</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#contact">
                        <span>Kontakt</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" data-bs-toggle="modal" data-bs-target="#loginmodal">
                        <span>Login</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" data-bs-toggle="modal" data-bs-target="#warenkorbmodal">
                        <span>
                            <i class="bi bi-basket2" style="font-size: 1.5em;"></i>
                        </span>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>