<nav class="navbar navbar-expand-lg">
    <div class="container justify-content-start gap-3 gap-lg-0">

        <ul class="navbar-nav me-auto order-lg-0">
            <li class="nav-item">
                <a class="nav-item" href="/">
                    <img src="src/img/logo.png" alt="logo" width="200">
                </a>
            </li>
        </ul>

        <ul class="navbar-nav order-lg-2">
            <?php if (!isset($_SESSION['admin'])): ?>
                <li class="nav-item">
                    <a id="shoppingcart_button" class="nav-link disabled position-relative" href="javascript:void(0);" data-bs-toggle="modal" data-bs-target="#modal_shoppingcart">
                        <span><i class="bi bi-basket2" style="font-size: 1.5em;"></i></span>
                        <span id="shoppingcart_counter" class="position-absolute top-50 translate-middle badge rounded-pill bg-danger" style="font-size: 0.5em;"></span>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
        
        <ul class="navbar-nav order-lg-2">
            <li class="nav-item">
                <a class="nav-link navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </a>
            </li>
        </ul>

        <div class="collapse navbar-collapse justify-content-lg-end" id="navbarNav">
            <ul class="navbar-nav align-items-center">
                <?php if (!isset($_SESSION['admin'])): ?>
                    <li class="nav-item">
                        <a class="nav-link" href="#foodmenu">
                            <span>Speisekarte</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#team">
                            <span>Team</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#contact">
                            <span>Kontakt</span>
                        </a>
                    </li>
                <?php endif; ?>
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0);" data-bs-toggle="modal" data-bs-target="#loginmodal">
                        <?php if (isset($_SESSION['user']) || isset($_SESSION['admin'])): ?>
                            <span>Logout</span>
                        <?php else: ?>
                            <span>Login</span>
                        <?php endif; ?>
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>