<div class="modal fade" id="loginmodal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Login</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="mb-3">
                        <label for="user" class="col-form-label">E-Mail</label>
                        <input type="email" class="form-control" id="user">
                    </div>
                    <div class="mb-3">
                        <label for="password" class="col-form-label">Passwort</label>
                        <input type="password" class="form-control" id="password">
                    </div>
                    <button type="submit" class="btn btn-primary">Anmelden</button>
                </form>
            </div>
        </div>
    </div>
</div>