<div class="modal fade" id="warenkorbmodal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5">Warenkorb</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <ul>
                    <li>food 1</li>
                    <li>food 2</li>
                    <li>food 3</li>
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">abbrechen</button>
                <button type="button" class="btn btn-primary">bestellen</button>
            </div>
        </div>
    </div>
</div>