<div class="container">
    <div class="row">
        <div class="col text-center">
            <h2>FUNNY DINNER CONTEST</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form>
                <div class="d-flex align-items-end gap-2 mb-3">
                    <button type="submit" class="btn btn-primary">Absenden</button>
                    <div class="item flex-fill">
                    <label class="form-label" for="link">Bitte Bild als Link einfügen:</label>
                    <input type="text" class="form-control" id="link" placeholder="http://image.com/">
                    </div>                
                </div>
            </form>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col">

            <div class="contest-carousel owl-carousel owl-theme">

                <div class="item text-center">
                    <a href="" class="image">
                        <img src="src/img/food/Weizenballchen-WRAP-1200x1433.png" class="img-fluid" alt="food" />
                    </a>
                    <a href="" class="like">
                        <i class="bi bi-heart"></i>
                        <i class="bi bi-heart-fill"></i>
                    </a>
                </div>

                <div class="item text-center">
                    <a href="" class="image">
                        <img src="src/img/food/Suffle-1200x1433.png" class="img-fluid" alt="food" />
                    </a>
                    <a href="" class="like">
                        <i class="bi bi-heart"></i>
                        <i class="bi bi-heart-fill"></i>
                    </a>
                </div>

                <div class="item text-center">
                    <a href="" class="image">
                        <img src="src/img/food/Profiterole-mit-dunkler-schokolade-1200x1433.png" class="img-fluid" alt="food" />
                    </a>
                    <a href="" class="like">
                        <i class="bi bi-heart"></i>
                        <i class="bi bi-heart-fill"></i>
                    </a>
                </div>

                <div class="item text-center">
                    <a href="" class="image">
                        <img src="src/img/food/mono-bella-white-chocolate-plate-1200x1432.png" class="img-fluid" alt="food" />
                    </a>
                    <a href="" class="like">
                        <i class="bi bi-heart"></i>
                        <i class="bi bi-heart-fill"></i>
                    </a>
                </div>

                <div class="item text-center">
                    <a href="" class="image">
                        <img src="src/img/food/Mini-Weizenballchen-1200x1433.png" class="img-fluid" alt="food" />
                    </a>
                    <a href="" class="like">
                        <i class="bi bi-heart"></i>
                        <i class="bi bi-heart-fill"></i>
                    </a>
                </div>

            </div>

        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <h2>WINNER WINNER CIGKÖFTE-DINNER</h2>
            <img src="src/img/food/Cigkoftem-WRAP-1200x1433.png" class="img-fluid" alt="" width="600" />   
        </div>
    </div>
</div>
