<div class="container">
    <div class="row">
        <div class="col text-center">
            <h2>KONTAKT</h2>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col">
            <h4 class="d-flex gap-3 align-items-center">
                <i class="bi bi-geo-alt-fill link-primary"></i>
                <span>ADRESSE</span>
            </h4>
            <p>Schweiggerstraße 3<br> 90478 Nürnberg</p>
        </div>
        <div class="col">
            <h4 class="d-flex gap-3 align-items-center">
                <i class="bi bi-telephone link-primary"></i>
                <span>TELEFON</span>
            </h4>
            <p><a href="tel:+4991199449155">0911 99449155</a></p>
        </div>
        <div class="col">
            <h4 class="d-flex gap-3 align-items-center">
                <i class="bi bi-envelope link-primary"></i>
                <span>E-Mail</span>
            </h4>
            <p><a href="mailto:info@cigkoeftem.de">info@cigkoeftem.de</a></p>
        </div>
        <div class="col d-flex gap-4 fs-2">
            <a href="" class="icon">
                <i class="bi bi-facebook"></i>
            </a>
            <a href="" class="icon">
                <i class="bi bi-instagram"></i>
            </a>
            <a href="" class="icon">
                <i class="bi bi-messenger"></i>
            </a>
            <a href="" class="icon">
                <i class="bi bi-whatsapp"></i>
            </a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2594.2668134373303!2d11.087643777478798!3d49.44167395948124!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x479f57745ac8a45b%3A0x769c2d1da9c2a00e!2sSchweiggerstra%C3%9Fe%203%2C%2090478%20N%C3%BCrnberg!5e0!3m2!1sde!2sde!4v1739060100356!5m2!1sde!2sde" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
</div>