<div class="container">
    <div class="row">
        <div class="col text-center">
            <h2>FUNNY DINNER CONTEST</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form id="uploadContestImage">
                <div class="d-flex align-items-end gap-2 mb-3">
                    <button type="submit" class="btn btn-primary">Absenden</button>
                    <div class="item flex-fill">
                        <label class="form-label" for="link">Bitte Bild als Link einfügen:</label>
                        <input type="text" name="imagePath" class="form-control" id="imagePath" placeholder="http://image.com/">
                    </div>
                </div>
            </form>
            <div id="uploadContestImageMessage">

            </div>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col">
            <div class="contest-carousel owl-carousel owl-theme"></div>
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <h2>WINNER WINNER CIGKÖFTE-DINNER</h2>
            <img src="<?=$data['contestWinner']['pic_url']?>" class="img-fluid rounded" alt="" width="600" />
        </div>
    </div>
</div>