<?php $articles = json_decode(file_get_contents('src/pseudo-articles.json'), true); // Pseudo-Artikel-Datenbank ?>

<div class="container">
    <div class="row mb-5">
        <div class="col text-center">
            <h2>Unere Spezialitäten</h2>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea illum assumenda accusantium laboriosam
                facere cupiditate quidem, quos quibusdam harum, eveniet culpa! Eaque sunt assumenda culpa dolore iusto
                officiis sint facilis animi. Doloremque quo eos quaerat quidem dolorum voluptatibus sequi, voluptatem ut
                possimus, odit ipsa earum fugiat similique maxime molestiae error.</p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="food-carousel owl-carousel owl-theme">

                <?php foreach ($articles as $article): ?>
                    <?php if ($article['special']):?>
                        <a href="#" class="item text-center" category="<?= $article['category']?>" ean="<?= $article['ean']?>" data-bs-toggle="modal" data-bs-target="#foodmodal">
                            <p class="image">
                                <img src="<?= $article['image']?>" class="img-fluid rounded" alt="food" />
                            </p>
                            <p class="textbox">
                                <span class="title"><b><?= $article['name']?></b></span><br>
                                <span class="price fw-light"><?= $article['price']?> €</span>
                            </p>
                            <div class="d-none">
                                <div class="description"><p><?= $article['description']?></p></div>
                                <div class="additives"><p><?=$article['additives']?></p></div>
                                <div class="calories"><p><?= $article['calories']?> Kalorien</p></div>
                            </div>
                        </a>
                    <?php endif; ?>
                <?php endforeach; ?>
                
            </div>
        </div>
    </div>
</div>