<div class="container">
    <div class="row mb-5">
        <div class="col text-center">
            <h2>Unere Spezialitäten</h2>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea illum assumenda accusantium laboriosam
                facere cupiditate quidem, quos quibusdam harum, eveniet culpa! Eaque sunt assumenda culpa dolore iusto
                officiis sint facilis animi. Doloremque quo eos quaerat quidem dolorum voluptatibus sequi, voluptatem ut
                possimus, odit ipsa earum fugiat similique maxime molestiae error.</p>
        </div>
    </div>
    <div class="row">
        <div class="col">

            <div class="food-carousel owl-carousel owl-theme">
                <a href="#" class="item text-center" category="sweets" ean="8" data-bs-toggle="modal"
                    data-bs-target="#foodmodal">
                    <p class="image">
                        <img src="src/img/food/Falafill-1200x1433.png" class="img-fluid" alt="food" />
                    </p>
                    <p class="textbox">
                        <span class="title"><b><?php $data['foodname'] ?></b></span><br>
                        <span class="price fw-light">25,- €</span>
                    </p>
                    <div class="d-none">
                        <div class="description">
                            <p> Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui quae quos aut magni neque
                                et
                                repellendus officia omnis possimus. Dolor alias saepe aperiam quasi similique assumenda?
                                Adipisci ipsum cupiditate nemo.</p>
                        </div>
                        <div class="additives">
                            <p>bla, bli, blub</p>
                        </div>
                        <div class="calories">
                            <p>400</p>
                        </div>
                    </div>
                </a>
                <!-- copy paste für Veranschaulichung: -->

                <a href="#" class="item text-center" category="sweets" ean="8" data-bs-toggle="modal"
                    data-bs-target="#foodmodal">
                    <p class="image">
                        <img src="src/img/food/Falafill-1200x1433.png" class="img-fluid" alt="food" />
                    </p>
                    <p class="textbox">
                        <span class="title"><b>Food Name</b></span><br>
                        <span class="price fw-light">25,- €</span>
                    </p>
                    <div class="d-none">
                        <div class="description">
                            <p> Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui quae quos aut magni neque
                                et
                                repellendus officia omnis possimus. Dolor alias saepe aperiam quasi similique assumenda?
                                Adipisci ipsum cupiditate nemo.</p>
                        </div>
                        <div class="additives">
                            <p>bla, bli, blub</p>
                        </div>
                        <div class="calories">
                            <p>400</p>
                        </div>
                    </div>
                </a>

                <a href="#" class="item text-center" category="sweets" ean="8" data-bs-toggle="modal"
                    data-bs-target="#foodmodal">
                    <p class="image">
                        <img src="src/img/food/Falafill-1200x1433.png" class="img-fluid" alt="food" />
                    </p>
                    <p class="textbox">
                        <span class="title"><b>Food Name</b></span><br>
                        <span class="price fw-light">25,- €</span>
                    </p>
                    <div class="d-none">
                        <div class="description">
                            <p> Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui quae quos aut magni neque
                                et
                                repellendus officia omnis possimus. Dolor alias saepe aperiam quasi similique assumenda?
                                Adipisci ipsum cupiditate nemo.</p>
                        </div>
                        <div class="additives">
                            <p>bla, bli, blub</p>
                        </div>
                        <div class="calories">
                            <p>400</p>
                        </div>
                    </div>
                </a>

                <a href="#" class="item text-center" category="sweets" ean="8" data-bs-toggle="modal"
                    data-bs-target="#foodmodal">
                    <p class="image">
                        <img src="src/img/food/Falafill-1200x1433.png" class="img-fluid" alt="food" />
                    </p>
                    <p class="textbox">
                        <span class="title"><b>Food Name</b></span><br>
                        <span class="price fw-light">25,- €</span>
                    </p>
                    <div class="d-none">
                        <div class="description">
                            <p> Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui quae quos aut magni neque
                                et
                                repellendus officia omnis possimus. Dolor alias saepe aperiam quasi similique assumenda?
                                Adipisci ipsum cupiditate nemo.</p>
                        </div>
                        <div class="additives">
                            <p>bla, bli, blub</p>
                        </div>
                        <div class="calories">
                            <p>400</p>
                        </div>
                    </div>
                </a>

                <a href="#" class="item text-center" category="sweets" ean="8" data-bs-toggle="modal"
                    data-bs-target="#foodmodal">
                    <p class="image">
                        <img src="src/img/food/Falafill-1200x1433.png" class="img-fluid" alt="food" />
                    </p>
                    <p class="textbox">
                        <span class="title"><b>Food Name</b></span><br>
                        <span class="price fw-light">25,- €</span>
                    </p>
                    <div class="d-none">
                        <div class="description">
                            <p> Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui quae quos aut magni neque
                                et
                                repellendus officia omnis possimus. Dolor alias saepe aperiam quasi similique assumenda?
                                Adipisci ipsum cupiditate nemo.</p>
                        </div>
                        <div class="additives">
                            <p>bla, bli, blub</p>
                        </div>
                        <div class="calories">
                            <p>400</p>
                        </div>
                    </div>
                </a>

                <a href="#" class="item text-center" category="sweets" ean="8" data-bs-toggle="modal"
                    data-bs-target="#foodmodal">
                    <p class="image">
                        <img src="src/img/food/Falafill-1200x1433.png" class="img-fluid" alt="food" />
                    </p>
                    <p class="textbox">
                        <span class="title"><b>Food Name</b></span><br>
                        <span class="price fw-light">25,- €</span>
                    </p>
                    <div class="d-none">
                        <div class="description">
                            <p> Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui quae quos aut magni neque
                                et
                                repellendus officia omnis possimus. Dolor alias saepe aperiam quasi similique assumenda?
                                Adipisci ipsum cupiditate nemo.</p>
                        </div>
                        <div class="additives">
                            <p>bla, bli, blub</p>
                        </div>
                        <div class="calories">
                            <p>400</p>
                        </div>
                    </div>
                </a>

            </div>

        </div>
    </div>
</div>