<?php $articles = json_decode(file_get_contents('src/pseudo-articles.json'), true); // Pseudo-Artikel-Datenbank ?>

<div class="container">
    <div class="row">
        <div class="col text-center">
            <h2>Speisekarte</h2>
        </div>
    </div>
    <div id="foodfilter">
        <div class="row">
            <div class="col-sm-12 d-flex flex-wrap justify-content-center mb-4">
                <button type="button" class="btn d-block m-1 active" category="all"><b>All</b></button>
                <?php $categories = []; foreach ($articles as $item) {$categories[$item["category"]] = true;} foreach (array_keys($categories) as $category): ?>
                    <button type="button" class="btn d-block m-1" category="<?=ucfirst($category)?>"><b><?=ucfirst($category)?></b></button>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <div id="foodlist">
        <div class="row row-cols-2 row-cols-sm-3 row-cols-md-4 row-cols-lg-5">

        <?php foreach ($articles as $article): ?>
            <a href="javascript();" class="item active col text-center" category="<?=$article['category']?>" ean="<?=$article['ean']?>" data-bs-toggle="modal" data-bs-target="#foodmodal">
                <p class="image mb-1">
                    <img src="<?=$article['image']?>" class="img-fluid rounded" alt="food" />
                </p>
                <p class="textbox">
                    <span class="title"><b><?=$article['name']?></b></span><br>
                    <span class="price fw-light"><?=$article['price']?> €</span>
                </p>
                <div class="d-none">
                    <div class="description"><p><?=$article['description']?></p></div>
                    <div class="additives"><p><?=$article['additives']?></p></div>
                    <div class="calories"><p><?=$article['calories']?> Kalorien</p></div>
                </div>
            </a>
        <?php endforeach; ?>

        </div>
    </div>
</div>