<div class="container">
    <div class="row mb-5">
        <div class="col text-center">
            <h2>Unere Spezialitäten</h2>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea illum assumenda accusantium laboriosam facere cupiditate quidem, quos quibusdam harum, eveniet culpa! Eaque sunt assumenda culpa dolore iusto officiis sint facilis animi. Doloremque quo eos quaerat quidem dolorum voluptatibus sequi, voluptatem ut possimus, odit ipsa earum fugiat similique maxime molestiae error.</p>
        </div>
    </div>
    <div class="row">
        <div class="col">

            <div class="food-carousel owl-carousel owl-theme">

                <a href="#" class="item text-center">
                    <p class="image">
                        <img src="src/img/food/Falafill-1200x1433.png" class="img-fluid" alt="food" />
                    </p>
                    <p class="textbox">
                        <span class="title"><b>Food Name</b></span><br>
                        <span class="price fw-light">25,- €</span>
                    </p>
                </a>

                <a href="#" class="item text-center">
                    <p class="image">
                        <img src="src/img/food/Falafill-1200x1433.png" class="img-fluid" alt="food" />
                    </p>
                    <p class="textbox">
                        <span class="title"><b>Food Name</b></span><br>
                        <span class="price fw-light">25,- €</span>
                    </p>
                </a>

                <a href="#" class="item text-center">
                    <p class="image">
                        <img src="src/img/food/Falafill-1200x1433.png" class="img-fluid" alt="food" />
                    </p>
                    <p class="textbox">
                        <span class="title"><b>Food Name</b></span><br>
                        <span class="price fw-light">25,- €</span>
                    </p>
                </a>

                <a href="#" class="item text-center">
                    <p class="image">
                        <img src="src/img/food/Falafill-1200x1433.png" class="img-fluid" alt="food" />
                    </p>
                    <p class="textbox">
                        <span class="title"><b>Food Name</b></span><br>
                        <span class="price fw-light">25,- €</span>
                    </p>
                </a>

                <a href="#" class="item text-center">
                    <p class="image">
                        <img src="src/img/food/Falafill-1200x1433.png" class="img-fluid" alt="food" />
                    </p>
                    <p class="textbox">
                        <span class="title"><b>Food Name</b></span><br>
                        <span class="price fw-light">25,- €</span>
                    </p>
                </a>

                <a href="#" class="item text-center">
                    <p class="image">
                        <img src="src/img/food/Falafill-1200x1433.png" class="img-fluid" alt="food" />
                    </p>
                    <p class="textbox">
                        <span class="title"><b>Food Name</b></span><br>
                        <span class="price fw-light">25,- €</span>
                    </p>
                </a>

            </div>

        </div>
    </div>
</div>