<div class="background"></div>
<div class="container">
    <div class="row">
        <div class="col text-center">
            <img src="src/img/logo.png" class="img-fluid mb-lg-5" alt="...">
        </div>
    </div>
    <div class="row align-items-center flex-md-row-reverse">

        <div class="col-md-12 col-lg-6">
            <img src="src\img\Cigkoeftem-veganlabel-produkte.png" class="img-fluid rounded-top" alt="Essen" />
        </div>
        <div class="col-md-12 col-lg-6">
            <h1 class="text-success-emphasis"><b>Vegan kann so anders <br>
                    Vegan kann so lecker</b></h1>
            <p>Bei Çiğköftem gibt es leckere und gesunde Gerichte, die das Wasser im Mund zusammenlaufen lassen. Hinzu kommt noch: Wir sind vegan!</p>
            <br>
            <br>
            <h2><b>Öffnungszeiten</b></h2>
            <table class="table" style="width: auto;">
                <tr>
                    <td class="day" style="padding-right: 1.5rem;">Montag</td>
                    <td class="time">12:00 - 21:00 Uhr</td>
                </tr>
                <tr>
                    <td class="day" style="padding-right: 1.5rem;">Dienstag</td>
                    <td class="time">12:00 - 21:00 Uhr</td>
                </tr>
                <tr>
                    <td class="day" style="padding-right: 1.5rem;">Mittwoch</td>
                    <td class="time">12:00 - 21:00 Uhr</td>
                </tr>
                <tr>
                    <td class="day" style="padding-right: 1.5rem;">Donnerstag</td>
                    <td class="time">12:00 - 21:00 Uhr</td>
                </tr>
                <tr>
                    <td class="day" style="padding-right: 1.5rem;">Freitag</td>
                    <td class="time">12:00 - 22:00 Uhr</td>
                </tr>
                <tr>
                    <td class="day" style="padding-right: 1.5rem;">Samstag</td>
                    <td class="time">12:00 - 22:00 Uhr</td>
                </tr>
                <tr>
                    <td class="day" style="padding-right: 1.5rem;">Sonntag</td>
                    <td class="time">12:00 - 21:00 Uhr</td>
                </tr>
            </table>
        </div>
    </div>
</div>