<div class="container">
    <div class="row">
        <div class="col-sm-12 col-lg-6">
            <img src="src/img/franchise-de-sube-1.jpg" class="img-fluid" alt=""/>
        </div>
        <div class="col-sm-12 col-lg-6">
            <h2>Unser Restaurant</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem labore adipisci dolor quos itaque eius totam veritatis eligendi ex, magnam cupiditate omnis enim doloremque suscipit aliquam ipsum praesentium consequuntur vitae ut soluta. Vel animi earum sed nostrum at eum eveniet nobis explicabo quos quibusdam, assumenda minima velit in voluptatibus rem.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem labore adipisci dolor quos itaque eius totam veritatis eligendi ex, magnam cupiditate omnis enim doloremque suscipit aliquam ipsum praesentium consequuntur vitae ut soluta. Vel animi earum sed nostrum at eum eveniet nobis explicabo quos quibusdam, assumenda minima velit in voluptatibus rem.</p>
        </div>
    </div>
</div>