<div class="container">
        <div class="row">
            <div class="col text-center">
                <h2>Unser Team</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">              
                <p><img src="src/img/team/chef-1.jpg" class="img-fluid rounded" alt="Teammitglied"></p>
                <h4>Papa Kip</h4>
                <p>Chef</p>
            </div>
            <div class="col-md-4">
                <p><img src="src/img/team/chef-2.jpg" class="img-fluid rounded" alt="Teammitglied"></p>
                <h4>Mama Kip</h4>
                <p>Köchin</p>
            </div>
            <div class="col-md-4">
                <p><img src="src/img/team/chef-3.jpg" class="img-fluid rounded" alt="Teammitglied"></p>
                <h4>Özer Kip</h4>
                <p>Service</p>
            </div>
        </div>
    </div>