<div class="container">
    <div class="row">
        <div class="col text-center">
            <h2>Registration</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form>
                <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 row-gap-3 mb-4">
                    <div class="col">
                        <label for="vorname" class="form-label">Vorname</label>
                        <input type="text" class="form-control" id="vorname">
                    </div>
                    <div class="col">
                        <label for="nachname" class="form-label">Nachname</label>
                        <input type="text" class="form-control" id="nachname">
                    </div>
                    <div class="col">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email">
                    </div>
                    <div class="col">
                        <label for="strasse" class="form-label">Straße</label>
                        <input type="text" class="form-control" id="strasse">
                    </div>
                    <div class="col">
                        <label for="plz" class="form-label">PLZ</label>
                        <input type="text" class="form-control" id="plz">
                    </div>
                    <div class="col">
                        <label for="wohnort" class="form-label">Wohnort</label>
                        <input type="text" class="form-control" id="wohnort">
                    </div>
                    <div class="col">
                        <label for="passwort" class="form-label">Passwort</label>
                        <input type="password" class="form-control" id="passwort">
                    </div>
                    <div class="col">
                        <label for="passwort_wiederholen" class="form-label">Passwort wiederholen</label>
                        <input type="password" class="form-control" id="passwort_wiederholen">
                    </div>
                    <div class="col d-grid align-items-center">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="datenschutz">
                            <label class="form-check-label" for="datenschutz">
                                Ich habe die Datenschutzerklärung gelesen und akzeptiert.
                            </label>
                        </div>
                    </div>
                    <div class="col d-grid">
                        <button type="submit" class="btn btn-primary">Registrieren</button>
                    </div>
                </div>
              
            </form>
        </div>
    </div>
</div>