<!DOCTYPE html>
<html lang="de" data-bs-theme="dark">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap 5.3 Website</title>
    <link rel="stylesheet" href="vendor/OwlCarousel2-2.3.4/dist/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="vendor/OwlCarousel2-2.3.4/dist/assets/owl.theme.default.min.css">
    <link rel="stylesheet" href="src/css/main.css">
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/OwlCarousel2-2.3.4/dist/owl.carousel.min.js"></script>
</head>

<body>
    <?php require('templates/partials/loginmodal.phtml'); ?>
    <?php require('templates/partials/warenkorbmodal.phtml'); ?>
    <?php require('templates/partials/foodmodal.phtml'); ?>
    <header class="fixed-top">
        <?php require('templates/partials/header.phtml'); ?>
    </header>