<!DOCTYPE html>
<html lang="de" data-bs-theme="dark">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Çiğköftem</title>
    <link rel="stylesheet" href="src/css/main.css">
    <script src="vendor/jquery/jquery.min.js"></script>
    <link rel="stylesheet" href="vendor/OwlCarousel2-2.3.4/dist/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="vendor/OwlCarousel2-2.3.4/dist/assets/owl.theme.default.min.css">
    <link rel="stylesheet" href="vendor/fancy-box/fancy-box.min.css">
</head>

<body id="top">
    <?php require('templates/partials/modal_shoppingcart.phtml'); ?>
    <?php require('templates/partials/modal_food.phtml'); ?>
    <?php require('templates/partials/modal_login.phtml'); ?>
    <header class="fixed-top">
        <?php require('templates/partials/header.phtml'); ?>
    </header>