<!DOCTYPE html>
<html lang="de" data-bs-theme="dark">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Çiğköftem</title>

    <link rel="apple-touch-icon" sizes="57x57" href="/src/img/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/src/img/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/src/img/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/src/img/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/src/img/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/src/img/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/src/img/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/src/img/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/src/img/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/src/img/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/src/img/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/src/img/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/src/img/favicon/favicon-16x16.png">

    <link rel="stylesheet" href="src/css/main.css">
    <script src="vendor/jquery/jquery.min.js"></script>
    <link rel="stylesheet" href="vendor/OwlCarousel2-2.3.4/dist/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="vendor/OwlCarousel2-2.3.4/dist/assets/owl.theme.default.min.css">
    <link rel="stylesheet" href="vendor/fancy-box/fancy-box.min.css">
</head>

<body id="top">
    <?php require('templates/partials/modal_shoppingcart.phtml'); ?>
    <?php require('templates/partials/modal_food.phtml'); ?>
    <?php require('templates/partials/modal_login.phtml'); ?>
    <header class="fixed-top">
        <?php require('templates/partials/header.phtml'); ?>
    </header>